function WC = wave_colors(obj) %#ok<INUSD>

WC = struct(...
      'stim_wave',          [1   1   1  ],     ...
      'stimulator_wave',    [1   1   0  ],     ...
      'stimulator_wave1',   [1   1   0  ],     ...
      'stimulator_wave2',   [1   1   0  ],     ...
      'stimulator_wave3',   [1   1   0  ],     ...
      'stimulator_wave4',   [1   1   0  ],     ...
      'stimulator_wave5',   [1   1   0  ]);